// flow-typed signature: 3dd2d6cc73a522a5f9b7fd724e23c3bc
// flow-typed version: <<STUB>>/graphql-s2s_v^0.18.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-s2s'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-s2s' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-s2s/src/graphmetadata' {
  declare module.exports: any;
}

declare module 'graphql-s2s/src/graphqls2s' {
  declare module.exports: any;
}

declare module 'graphql-s2s/src/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-s2s/src/graphmetadata.js' {
  declare module.exports: $Exports<'graphql-s2s/src/graphmetadata'>;
}
declare module 'graphql-s2s/src/graphqls2s.js' {
  declare module.exports: $Exports<'graphql-s2s/src/graphqls2s'>;
}
declare module 'graphql-s2s/src/utilities.js' {
  declare module.exports: $Exports<'graphql-s2s/src/utilities'>;
}
